######################################################################
# Automatically generated by qmake (3.0) Thu Oct 11 22:09:44 2018
######################################################################

TEMPLATE = app
TARGET = templates_iterators
INCLUDEPATH += .

CONFIG += c++11

# Input
HEADERS += inc/Animal.h
SOURCES += iterator.cpp src/Animal.cpp
